import { useRouter } from "expo-router";
import React,{useState} from "react";
import {KeyboardAvoidingView,Platform,ScrollView,StyleSheet,Text,TextInput,TouchableOpacity} from "react-native";
import {SafeAreaView} from "react-native-safe-area-context";
import {api} from "@/services/api";
import {OtpInput} from "@/components/OtpInput";
import Toast from "react-native-toast-message";
type Response={success:boolean;message:string;testOtp?:string};
export default function ForgotPin(){const router=useRouter();const [phone,setPhone]=useState("+91");const [otp,setOtp]=useState("");const [pin,setPin]=useState("");const [confirm,setConfirm]=useState("");const [sent,setSent]=useState(false);const [testOtp,setTestOtp]=useState("");const [error,setError]=useState("");const [loading,setLoading]=useState(false);const number=phone.replace(/[^\d+]/g,"");
const send=async()=>{setError("");if(!/^\+[1-9]\d{7,14}$/.test(number))return setError("Enter a valid WhatsApp number with country code.");setLoading(true);const r=await api.post<Response>("/auth/forgot-pin",{phoneNumber:number},{skipAuth:true});setLoading(false);if(!r.success||!r.data)return setError(r.error||"Could not generate OTP.");setTestOtp(r.data.testOtp||"");setSent(true)};
const reset=async()=>{setError("");if(!/^\d{6}$/.test(otp))return setError("Enter the 6-digit OTP.");if(!/^\d{6}$/.test(pin))return setError("PIN must be exactly 6 digits.");if(pin!==confirm)return setError("PINs do not match.");setLoading(true);const r=await api.post<Response>("/auth/reset-pin",{phoneNumber:number,otp,newPin:pin},{skipAuth:true});setLoading(false);if(!r.success)return setError(r.error||"PIN reset failed.");Toast.show({type:"success",text1:"OTP verified",text2:"Your PIN was reset successfully."});router.replace("/")};
return <SafeAreaView style={s.safe}><KeyboardAvoidingView style={s.safe} behavior={Platform.OS==="ios"?"padding":"height"}><ScrollView contentContainerStyle={s.container} keyboardShouldPersistTaps="handled"><Text style={s.header}>Forgot PIN</Text>{!sent?<><TextInput style={s.input} placeholder="WhatsApp number, e.g. +919876543210" value={phone} onChangeText={setPhone} keyboardType="phone-pad"/><TouchableOpacity style={s.button} onPress={send} disabled={loading}><Text style={s.buttonText}>{loading?"Generating...":"Get WhatsApp OTP"}</Text></TouchableOpacity></>:<><Text style={s.info}>Enter the 6-digit verification code</Text>{testOtp?<Text style={s.test}>TEST OTP: {testOtp}</Text>:null}<OtpInput value={otp} onChange={setOtp} hasError={Boolean(error)}/><TextInput style={s.input} placeholder="New 6-digit PIN" value={pin} onChangeText={v=>setPin(v.replace(/\D/g,""))} keyboardType="number-pad" secureTextEntry maxLength={6}/><TextInput style={s.input} placeholder="Confirm new PIN" value={confirm} onChangeText={v=>setConfirm(v.replace(/\D/g,""))} keyboardType="number-pad" secureTextEntry maxLength={6}/><TouchableOpacity style={s.button} onPress={reset} disabled={loading}><Text style={s.buttonText}>{loading?"Resetting...":"Reset PIN"}</Text></TouchableOpacity></>}{error?<Text style={s.error}>{error}</Text>:null}</ScrollView></KeyboardAvoidingView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#fff"},container:{flexGrow:1,backgroundColor:"#fff",justifyContent:"center",padding:24,paddingBottom:32},header:{fontSize:26,fontWeight:"700",marginBottom:30,textAlign:"center",color:"#242424"},input:{backgroundColor:"#F2F2F2",color:"#242424",padding:16,borderRadius:14,marginBottom:16},button:{backgroundColor:"#FF6B4A",padding:18,borderRadius:16,alignItems:"center"},buttonText:{color:"#fff",fontWeight:"700",fontSize:16},info:{color:"#555",textAlign:"center",marginBottom:16},error:{color:"#B42318",marginTop:14,textAlign:"center"},test:{backgroundColor:"#ECFDF3",color:"#067647",padding:14,borderRadius:12,textAlign:"center",fontSize:20,fontWeight:"800",marginBottom:16}});
