import { useRouter } from "expo-router";
import React,{useState} from "react";
import {Image,KeyboardAvoidingView,Platform,Pressable,ScrollView,StyleSheet,Text,TextInput,TouchableOpacity,View} from "react-native";
import {SafeAreaView} from "react-native-safe-area-context";
import {StatusBar} from "expo-status-bar";
import {api} from "@/services/api";
import {AuthUser,saveAuth} from "@/store/authStore";
import {registerPushNotifications} from "@/services/notifications";
import {OtpInput} from "@/components/OtpInput";
import Toast from "react-native-toast-message";
type Step="phone"|"otp"|"pin";
type OtpResponse={success:boolean;message:string;testOtp?:string};
type VerifyResponse={success:boolean;message:string;loginChallenge:string};
type AuthResponse={success:boolean;token:string;user:AuthUser};
export default function Login(){const router=useRouter();const [step,setStep]=useState<Step>("phone");const [phoneInput,setPhoneInput]=useState("+91");const [otp,setOtp]=useState("");const [pin,setPin]=useState("");const [testOtp,setTestOtp]=useState("");const [challenge,setChallenge]=useState("");const [showPin,setShowPin]=useState(false);const [error,setError]=useState("");const [loading,setLoading]=useState(false);const phone=phoneInput.replace(/[^\d+]/g,"");
const requestOtp=async()=>{setError("");if(!/^\+[1-9]\d{7,14}$/.test(phone))return setError("Enter a valid WhatsApp number with country code.");setLoading(true);const r=await api.post<OtpResponse>("/auth/request-login-otp",{phoneNumber:phone},{skipAuth:true});setLoading(false);if(!r.success||!r.data)return setError(r.error||"Could not generate OTP.");setTestOtp(r.data.testOtp||"");setStep("otp")};
const verifyOtp=async()=>{setError("");if(!/^\d{6}$/.test(otp))return setError("Enter the 6-digit OTP.");setLoading(true);const r=await api.post<VerifyResponse>("/auth/verify-login-otp",{phoneNumber:phone,otp},{skipAuth:true});setLoading(false);if(!r.success||!r.data)return setError(r.error||"OTP verification failed.");Toast.show({type:"success",text1:"OTP verified",text2:"Verification completed successfully."});setChallenge(r.data.loginChallenge);setStep("pin")};
const login=async()=>{setError("");if(!/^\d{6}$/.test(pin))return setError("Enter your 6-digit PIN.");setLoading(true);const r=await api.post<AuthResponse>("/auth/login",{phoneNumber:phone,pin,loginChallenge:challenge},{skipAuth:true});setLoading(false);if(!r.success||!r.data)return setError(r.error||"Login failed.");await saveAuth(r.data.token,r.data.user);router.replace(r.data.user.role==="admin"?"/(admin)/dashboard":"/(app)/home");Toast.show({type:"success",text1:"Login successful"});void registerPushNotifications()};
return <SafeAreaView style={s.safe} edges={["top","right","bottom","left"]}><StatusBar style="dark" backgroundColor="#FFFFFF"/><KeyboardAvoidingView style={s.keyboard} behavior={Platform.OS==="ios"?"padding":"height"}><ScrollView contentContainerStyle={s.container} keyboardShouldPersistTaps="handled"><View style={s.logoBox}><Image source={require("../assets/images/happinotes-logo.png")} style={s.logo} resizeMode="contain"/></View><Text style={s.title}>{step==="phone"?"Welcome Back":step==="otp"?"Verify WhatsApp":"Enter Your PIN"}</Text>
{step==="phone"?<><TextInput placeholder="WhatsApp number, e.g. +919876543210" style={s.input} value={phoneInput} onChangeText={setPhoneInput} keyboardType="phone-pad"/><TouchableOpacity style={s.button} onPress={requestOtp} disabled={loading}><Text style={s.buttonText}>{loading?"Generating...":"Continue"}</Text></TouchableOpacity></>:null}
{step==="otp"?<><Text style={s.info}>Enter the 6-digit code sent to {phone}</Text>{testOtp?<Text style={s.testOtp}>DEMO OTP: {testOtp}</Text>:null}<OtpInput value={otp} onChange={setOtp} hasError={Boolean(error)}/><TouchableOpacity style={s.button} onPress={verifyOtp} disabled={loading}><Text style={s.buttonText}>{loading?"Verifying...":"Verify OTP"}</Text></TouchableOpacity><Pressable onPress={()=>setStep("phone")}><Text style={s.link}>Change number</Text></Pressable></>:null}
{step==="pin"?<><Text style={s.info}>OTP verified successfully</Text><View style={s.pinBox}><TextInput placeholder="6-digit PIN" style={s.pinInput} value={pin} onChangeText={v=>setPin(v.replace(/\D/g,""))} keyboardType="number-pad" maxLength={6} secureTextEntry={!showPin}/><TouchableOpacity onPress={()=>setShowPin(v=>!v)}><Text style={s.eye}>{showPin?"Hide":"Show"}</Text></TouchableOpacity></View><TouchableOpacity style={s.button} onPress={login} disabled={loading}><Text style={s.buttonText}>{loading?"Logging in...":"Enter App"}</Text></TouchableOpacity></>:null}
{error?<Text style={s.error}>{error}</Text>:null}<Pressable onPress={()=>router.push("/forgot-password")}><Text style={s.link}>Forgot PIN?</Text></Pressable><Pressable onPress={()=>router.push("/signup")}><Text style={s.link}>Don&apos;t have an account? Sign Up</Text></Pressable></ScrollView></KeyboardAvoidingView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#fff"},keyboard:{flex:1},container:{backgroundColor:"#fff",flexGrow:1,justifyContent:"center",padding:24,paddingBottom:32},logoBox:{alignItems:"center",marginBottom:20},logo:{width:150,height:130},title:{fontSize:28,fontWeight:"700",textAlign:"center",marginBottom:24},input:{backgroundColor:"#F2F2F2",padding:16,borderRadius:14,marginBottom:16},button:{backgroundColor:"#FF6B4A",padding:18,borderRadius:16,alignItems:"center",marginTop:8},buttonText:{color:"#fff",fontWeight:"700",fontSize:16},info:{textAlign:"center",color:"#555",marginBottom:14},testOtp:{backgroundColor:"#ECFDF3",color:"#067647",padding:14,borderRadius:12,textAlign:"center",fontSize:20,fontWeight:"800",marginBottom:16},pinBox:{flexDirection:"row",alignItems:"center",backgroundColor:"#F2F2F2",borderRadius:14,marginBottom:10},pinInput:{flex:1,padding:16},eye:{color:"#FF6B4A",fontWeight:"700",paddingHorizontal:15},error:{color:"#B42318",textAlign:"center",marginTop:14},link:{marginTop:18,textAlign:"center",color:"#555",fontWeight:"600"}});
