import { useCallback, useEffect, useState } from "react";
import { Alert, FlatList, Image, Pressable, RefreshControl, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import Toast from "react-native-toast-message";
import { api } from "@/services/api";
import type { Book } from "@/types/book";
import { useRealtime } from "@/contexts/RealtimeContext";

export default function ManageBooks(){
 const router=useRouter();const {booksRevision,connected}=useRealtime();const [books,setBooks]=useState<Book[]>([]);const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [error,setError]=useState("");
 const load=useCallback(async()=>{const result=await api.get<{success:boolean;books:Book[]}>("/admin/books");if(result.success&&result.data){setBooks(result.data.books);setError("");}else setError(result.error||"Could not load catalog.");},[]);
 useEffect(()=>{load().finally(()=>setLoading(false));},[load,booksRevision]);
 const refresh=async()=>{setRefreshing(true);await load();setRefreshing(false)};
 const remove=(book:Book)=>Alert.alert("Delete this book?",`“${book.title}” and all its chapters will be permanently deleted.`,[{text:"Cancel",style:"cancel"},{text:"Delete",style:"destructive",onPress:async()=>{const result=await api.delete<{success:boolean}>(`/admin/books/${book._id}`);if(result.success){setBooks(v=>v.filter(x=>x._id!==book._id));Toast.show({type:"success",text1:"Book deleted"});}else Alert.alert("Delete failed",result.error||"Please try again.");}}]);
 return <View style={styles.screen}><View style={styles.header}><View style={styles.headerTop}><View><Text style={styles.eyebrow}>CATALOG / {books.length} EDITIONS</Text><Text style={styles.title}>Books desk</Text></View><Pressable accessibilityRole="button" onPress={()=>router.push("/(admin)/create-book")} style={styles.add}><Text style={styles.addText}>＋ Add book</Text></Pressable></View><View style={styles.sync}><View style={[styles.dot,connected&&styles.dotLive]}/><Text style={styles.syncText}>{connected?"Live sync connected":"Sync reconnecting"}</Text></View></View>
 {error?<View style={styles.errorBox}><Text accessibilityRole="alert" style={styles.error}>{error}</Text><Pressable onPress={load}><Text style={styles.retry}>Try again</Text></Pressable></View>:null}
 <FlatList data={books} keyExtractor={b=>b._id} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh} tintColor="#FF6B4A"/>} contentContainerStyle={styles.list} ListEmptyComponent={!loading?<View style={styles.empty}><Text style={styles.emptyTitle}>The shelf is waiting.</Text><Text style={styles.emptyBody}>Create the first edition. Books marked live appear instantly in listener apps.</Text><Pressable onPress={()=>router.push("/(admin)/create-book")}><Text style={styles.emptyLink}>Create a book →</Text></Pressable></View>:<Text style={styles.loading}>Loading catalog…</Text>} renderItem={({item})=><View style={styles.card}><View style={[styles.rail,item.status==="live"&&styles.railLive,item.status==="upcoming"&&styles.railUpcoming]}/>{item.coverImageUrl?<Image source={{uri:item.coverImageUrl}} style={styles.cover}/>:<View style={styles.placeholder}><Text style={styles.initial}>{item.title.charAt(0).toUpperCase()}</Text></View>}<View style={styles.body}><Text style={styles.bookTitle} numberOfLines={2}>{item.title}</Text><Text style={styles.meta}>{item.language} · {item.category}</Text><View style={styles.chips}><Text style={[styles.chip,item.status==="live"&&styles.liveChip,item.status==="upcoming"&&styles.upcomingChip]}>{item.status}</Text><Text style={styles.access}>{item.accessType}</Text></View><View style={styles.actions}><Pressable accessibilityLabel={`Edit ${item.title}`} onPress={()=>router.push({pathname:"/(admin)/edit-book",params:{id:item._id}})} style={styles.edit}><Text style={styles.editText}>Edit</Text></Pressable><Pressable accessibilityLabel={`Delete ${item.title}`} onPress={()=>remove(item)} style={styles.delete}><Text style={styles.deleteText}>Delete</Text></Pressable></View></View></View>}/>
 </View>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:"#F7F3EE"},header:{backgroundColor:"#181818",padding:20,paddingBottom:16},headerTop:{alignItems:"center",flexDirection:"row",gap:12,justifyContent:"space-between"},eyebrow:{color:"#E8DDD5",fontSize:11,fontWeight:"800",letterSpacing:1},title:{color:"#FFF",flexShrink:1,fontSize:30,fontWeight:"900",marginTop:4},add:{backgroundColor:"#FF6B4A",borderRadius:8,minHeight:46,justifyContent:"center",paddingHorizontal:14},addText:{color:"#FFF",fontWeight:"900"},sync:{alignItems:"center",flexDirection:"row",gap:7,marginTop:15},dot:{backgroundColor:"#8A817B",borderRadius:4,height:8,width:8},dotLive:{backgroundColor:"#45C676"},syncText:{color:"#CFC6BE",flexShrink:1,fontSize:12,fontWeight:"700"},list:{padding:16,paddingBottom:50},card:{backgroundColor:"#FFF",borderRadius:8,flexDirection:"row",marginBottom:12,overflow:"hidden",minHeight:164},rail:{backgroundColor:"#A8A29E",width:5},railLive:{backgroundColor:"#228B54"},railUpcoming:{backgroundColor:"#D98B18"},cover:{height:164,width:108},placeholder:{alignItems:"center",backgroundColor:"#EAE3DC",height:164,justifyContent:"center",width:108},initial:{color:"#716860",fontSize:38,fontWeight:"900"},body:{flex:1,minWidth:0,padding:14},bookTitle:{color:"#181818",fontSize:18,fontWeight:"900"},meta:{color:"#6E655F",fontSize:12,marginTop:5,textTransform:"capitalize"},chips:{flexDirection:"row",flexWrap:"wrap",gap:8,marginTop:11},chip:{backgroundColor:"#ECE8E4",borderRadius:5,color:"#5E5752",fontSize:11,fontWeight:"900",overflow:"hidden",paddingHorizontal:8,paddingVertical:5,textTransform:"uppercase"},liveChip:{backgroundColor:"#DDF5E6",color:"#176B3C"},upcomingChip:{backgroundColor:"#FFF0D5",color:"#995D08"},access:{color:"#6E655F",fontSize:11,fontWeight:"800",paddingVertical:5,textTransform:"uppercase"},actions:{flexDirection:"row",flexWrap:"wrap",gap:8,marginTop:14},edit:{alignItems:"center",backgroundColor:"#181818",borderRadius:7,justifyContent:"center",minHeight:40,paddingHorizontal:14},editText:{color:"#FFF",fontWeight:"800"},delete:{alignItems:"center",borderColor:"#D7CEC7",borderRadius:7,borderWidth:1,justifyContent:"center",minHeight:40,paddingHorizontal:10},deleteText:{color:"#B42318",fontWeight:"800"},empty:{alignItems:"center",paddingHorizontal:20,paddingVertical:45},emptyTitle:{color:"#181818",fontSize:23,fontWeight:"900",textAlign:"center"},emptyBody:{color:"#6E655F",lineHeight:21,marginTop:9,textAlign:"center"},emptyLink:{color:"#FF6B4A",fontWeight:"900",marginTop:18},loading:{color:"#6E655F",padding:40,textAlign:"center"},errorBox:{backgroundColor:"#FFF0EE",padding:12},error:{color:"#B42318",textAlign:"center"},retry:{color:"#B42318",fontWeight:"900",marginTop:6,textAlign:"center"}});
